function Residuals = UnbuckledRodSloughingBCs(Ml, Mr, modelParams)

Residuals = [Ml(1, 1), ...
            Ml(2, 1), ...
            Mr(3, 1), ...
            Mr(4, 1), ...
            Ml(1, 2) - Mr(1, 1), ...
            Ml(2, 2) - Mr(2, 1), ...
            Ml(3, 2) - Mr(3, 1), ...
            Ml(4, 2) - Mr(4, 1)];
