function Residuals = SloughingBCs(Ml, Mr, parameters)

y0 = parameters.y0;

Residuals = [Ml(1, 1), ...
            Ml(2, 1), ...
            Ml(5, 1), ...
            Ml(6, 1), ...
            Mr(2, 1) - 0.5, ... 
            Mr(3, 1) - y0, ...
            Mr(6, 1), ...
            Ml(1, 2) - Mr(1, 1), ...
            Ml(2, 2) - Mr(2, 1), ...
            Ml(3, 2) - Mr(3, 1), ...
            Ml(4, 2) - Mr(4, 1), ...
            Ml(5, 2) - Mr(5, 1), ...
            Ml(6, 2) - Mr(6, 1), ...
            Ml(7, 2) - Mr(7, 1)];
